TOP?=$(shell cd ../..;pwd)

include $(TOP)/dev/config.mak

EXTRA_RULE+= 

DIRECTORIES = \
	statusmanager \
	fetcher \
	utilities \
	osspecializationreader \
	osconfigurator \
	main

include $(TOP)/dev/tools/build/rules.mak

