/**
 *  Copyright (c) Microsoft Corporation
 *
 *  All rights reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"); you may not
 *  use this file except in compliance with the License. You may obtain a copy
 *  of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 *  THIS CODE IS PROVIDED *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 *  WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 *  MERCHANTABLITY OR NON-INFRINGEMENT.
 *
 *  See the Apache Version 2.0 License for specific language governing
 *  permissions and limitations under the License.
 *
 **/

/**                                                                             
    \file                                                                       
                                                                                
    \brief       Auto generated file containing build version information       
                                                                                
    \author      Automated Build System                                         
                                                                                
    DO NOT EDIT THIS FILE!                                                      
    DO NOT CHECK IN THIS FILE!                                                  
*/                                                                              
/*----------------------------------------------------------------------------*/
#ifndef VMM_BUILDVERSION_H                                                      
#define VMM_BUILDVERSION_H                                                      
                                                                                
int const VMM_BUILDVERSION_MAJOR   = 1;                              
                                                                                
int const VMM_BUILDVERSION_MINOR   = 0;                              
                                                                                
int const VMM_BUILDVERSION_PATCH   = 2;                              
                                                                                
int const VMM_BUILDVERSION_BUILDNR = 1065;                            
                                                                                
#endif // VMM_BUILDVERSION_H                                                    
